In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### SVM (Support Vector Machine)

It is basically is classification technique.

setter = suppport vectors, i.e. they are the last instance for their class from whoch the distance will be equalised.

best hyperplane which is euidistance to all support vectors


small margin vs large margin(choice of support vectors)

small - there is chance of misprediction


In [16]:
data=pd.read_csv("..\Dataset\iris.csv")
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['species']=le.fit_transform(data['species'])
data.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [45]:
from sklearn.model_selection import train_test_split
X=data.iloc[:,0:4]
y=data.iloc[:,4]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [54]:
from sklearn.svm import SVC
svc=SVC(kernel='linear')
model=svc.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(y_test.values)
print()
print(y_pred)

[0 0 0 2 0 1 0 1 0 2 1 0 0 2 2 2 0 1 2 0 0 1 2 0 2 2 2 0 2 0]

[0 0 0 2 0 1 0 1 0 2 1 0 0 2 2 2 0 1 2 0 0 1 2 0 2 2 2 0 2 0]


In [55]:
from sklearn import metrics

cnf=metrics.confusion_matrix(y_test,y_pred)
print(cnf)
print()
print("Accuracy: ",metrics.accuracy_score(y_test,y_pred))
print("Precision: ",metrics.precision_score(y_test,y_pred,average='weighted'))
print("Recall: ",metrics.recall_score(y_test,y_pred,average='weighted'))
print("f1 score: ",metrics.f1_score(y_test,y_pred,average='weighted'))

[[14  0  0]
 [ 0  5  0]
 [ 0  0 11]]

Accuracy:  1.0
Precision:  1.0
Recall:  1.0
f1 score:  1.0


In [86]:
data=pd.read_csv('../Dataset/winequality_red.csv')
X=data.drop(columns='quality')
y=data['quality']

In [87]:
from sklearn.preprocessing import StandardScaler
std_scaler=StandardScaler()
X=std_scaler.fit_transform(X)

In [88]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [89]:
from sklearn.svm import SVC
svc_rbf=SVC(kernel='rbf')
svc_linear=SVC(kernel='linear')
svc_poly=SVC(kernel='poly')
model_rbf=svc_rbf.fit(X_train,y_train)
model_linear=svc_linear.fit(X_train,y_train)
model_poly=svc_poly.fit(X_train,y_train)
y_pred_rbf=model_rbf.predict(X_test)
y_pred_linear=model_linear.predict(X_test)
y_pred_poly=model_poly.predict(X_test)

In [90]:
# from sklearn import metrics

# cnf=metrics.confusion_matrix(y_test,y_pred)
# print(cnf)
# print()
# print("Accuracy: ",metrics.accuracy_score(y_test,y_pred))
# print("Precision: ",metrics.precision_score(y_test,y_pred,average='weighted'))
# print("Recall: ",metrics.recall_score(y_test,y_pred,average='weighted'))
# print("f1 score: ",metrics.f1_score(y_test,y_pred,average='weighted'))

In [91]:
# from sklearn.metrics import classification_report
# report=classification_report(y_test,y_pred)
# print(report)

In [92]:
print("Accuracy using poly: ",metrics.accuracy_score(y_test,y_pred_poly))
print("Accuracy using linear: ",metrics.accuracy_score(y_test,y_pred_linear))
print("Accuracy using rbf: ",metrics.accuracy_score(y_test,y_pred_rbf))

Accuracy using poly:  0.653125
Accuracy using linear:  0.6
Accuracy using rbf:  0.64375
