In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### PCA



In [7]:
data=pd.read_csv('../Dataset/winequality_red.csv')
data.head(20)
# data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.4             0.700         0.00             1.9      0.076   
1             7.8             0.880         0.00             2.6      0.098   
2             7.8             0.760         0.04             2.3      0.092   
3            11.2             0.280         0.56             1.9      0.075   
4             7.4             0.700         0.00             1.9      0.076   
5             7.4             0.660         0.00             1.8      0.075   
6             7.9             0.600         0.06             1.6      0.069   
7             7.3             0.650         0.00             1.2      0.065   
8             7.8             0.580         0.02             2.0      0.073   
9             7.5             0.500         0.36             6.1      0.071   
10            6.7             0.580         0.08             1.8      0.097   
11            7.5             0.500         0.36             6.1      0.071   
12            5.6             0.615         0.00             1.6      0.089   
13            7.8             0.610         0.29             1.6      0.114   
14            8.9             0.620         0.18             3.8      0.176   
15            8.9             0.620         0.19             3.9      0.170   
16            8.5             0.280         0.56             1.8      0.092   
17            8.1             0.560         0.28             1.7      0.368   
18            7.4             0.590         0.08             4.4      0.086   
19            7.9             0.320         0.51             1.8      0.341   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  11.0                  34.0   0.9978  3.51       0.56   
1                  25.0                  67.0   0.9968  3.20       0.68   
2                  15.0                  54.0   0.9970  3.26       0.65   
3                  17.0                  60.0   0.9980  3.16       0.58   
4                  11.0                  34.0   0.9978  3.51       0.56   
5                  13.0                  40.0   0.9978  3.51       0.56   
6                  15.0                  59.0   0.9964  3.30       0.46   
7                  15.0                  21.0   0.9946  3.39       0.47   
8                   9.0                  18.0   0.9968  3.36       0.57   
9                  17.0                 102.0   0.9978  3.35       0.80   
10                 15.0                  65.0   0.9959  3.28       0.54   
11                 17.0                 102.0   0.9978  3.35       0.80   
12                 16.0                  59.0   0.9943  3.58       0.52   
13                  9.0                  29.0   0.9974  3.26       1.56   
14                 52.0                 145.0   0.9986  3.16       0.88   
15                 51.0                 148.0   0.9986  3.17       0.93   
16                 35.0                 103.0   0.9969  3.30       0.75   
17                 16.0                  56.0   0.9968  3.11       1.28   
18                  6.0                  29.0   0.9974  3.38       0.50   
19                 17.0                  56.0   0.9969  3.04       1.08   

    alcohol  quality  
0       9.4        5  
1       9.8        5  
2       9.8        5  
3       9.8        6  
4       9.4        5  
5       9.4        5  
6       9.4        5  
7      10.0        7  
8       9.5        7  
9      10.5        5  
10      9.2        5  
11     10.5        5  
12      9.9        5  
13      9.1        5  
14      9.2        5  
15      9.2        5  
16     10.5        7  
17      9.3        5  
18      9.0        4  
19      9.2        6

In [8]:
# read file
# extract features(X) and target value(y)
# scalling
# apply PCA
# train test split
# use logistic regression 
# evaluate the performance

In [15]:
X=data.drop(columns='quality')
y=data['quality']

In [19]:
from sklearn.preprocessing import StandardScaler
std_scaler=StandardScaler()
std_X=std_scaler.fit_transform(X)
print(std_X)

[[-0.52835961  0.96187667 -1.39147228 ...  1.28864292 -0.57920652
  -0.96024611]
 [-0.29854743  1.96744245 -1.39147228 ... -0.7199333   0.1289504
  -0.58477711]
 [-0.29854743  1.29706527 -1.18607043 ... -0.33117661 -0.04808883
  -0.58477711]
 ...
 [-1.1603431  -0.09955388 -0.72391627 ...  0.70550789  0.54204194
   0.54162988]
 [-1.39015528  0.65462046 -0.77526673 ...  1.6773996   0.30598963
  -0.20930812]
 [-1.33270223 -1.21684919  1.02199944 ...  0.51112954  0.01092425
   0.54162988]]


In [40]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
X_pca=pca.fit_transform(std_X)
print(X_pca)

[[-1.61952988  0.45095009]
 [-0.79916993  1.85655306]
 [-0.74847909  0.88203886]
 ...
 [-1.45612897  0.31174559]
 [-2.27051793  0.97979111]
 [-0.42697475 -0.53669021]]


In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_pca,y,test_size=0.20,random_state=0)
print(X_train)
print(X_test)

[[ 1.07318133  0.24910691]
 [ 1.95071383 -0.02864274]
 [ 1.58900572 -1.90400182]
 ...
 [ 0.07694682  0.53468983]
 [ 3.06287869 -0.86823376]
 [ 0.16187373  3.81606933]]
[[ 2.27124327e+00  7.07091623e-01]
 [-7.45522357e-01  4.53489905e-01]
 [ 4.49540353e-01 -1.81235713e+00]
 [ 7.75681245e-01 -9.76331799e-01]
 [ 2.06607479e+00 -2.10310339e+00]
 [ 6.04238778e-01  6.64695725e-01]
 [ 3.16892474e-01 -7.04514006e-01]
 [ 1.13888517e-01  5.34935175e-01]
 [-1.39193718e+00 -1.20207154e-01]
 [-6.88562501e-01  1.27519026e+00]
 [ 5.05038682e-01 -9.29670695e-01]
 [ 9.27285335e-01 -4.03719565e-01]
 [ 8.46605542e-01 -9.02734857e-01]
 [-4.06524093e+00  1.59453128e+00]
 [-2.50351561e+00 -6.77437138e-03]
 [-7.14809464e-02  1.45856679e-02]
 [-4.69670597e-01 -3.09135737e+00]
 [ 1.38377867e+00 -1.25171846e+00]
 [-3.18954435e+00 -1.49891921e+00]
 [-7.22438308e-01  5.04671914e-01]
 [-2.42706254e+00 -2.01161617e+00]
 [ 1.35354206e+00 -4.54810315e-01]
 [-1.51075804e+00 -5.30396787e-01]
 [ 2.94449496e-01  1.870927

In [42]:
from sklearn.linear_model import LogisticRegression
lgt=LogisticRegression()
model=lgt.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(y_pred)
print(np.array(y_test))

[5 5 6 6 7 5 6 5 6 5 6 6 6 5 5 5 7 6 6 5 6 6 6 5 5 5 5 6 5 6 6 5 5 5 5 6 5
 5 6 6 5 6 6 7 6 5 6 5 6 6 6 5 5 6 5 5 5 6 6 6 5 5 5 6 5 6 6 6 6 6 5 5 5 5
 5 6 6 5 5 6 5 5 6 6 5 5 5 6 6 5 5 5 6 6 6 5 6 6 6 6 6 6 5 6 6 6 6 5 6 5 6
 5 6 5 6 5 6 6 6 6 5 6 5 5 5 6 5 5 6 6 5 6 6 6 6 5 6 5 6 6 6 5 6 5 6 6 6 7
 6 6 6 6 5 6 6 5 5 6 6 5 6 6 6 5 6 5 5 6 5 6 5 5 5 7 5 6 6 6 6 5 5 6 5 5 7
 5 5 5 5 5 6 6 6 6 5 5 6 5 5 5 5 6 5 6 5 5 5 6 6 5 6 5 5 5 5 5 6 6 5 5 5 6
 6 6 5 5 6 6 6 6 5 6 5 5 6 5 6 6 7 6 5 5 5 5 6 5 5 5 5 6 5 5 5 6 6 5 5 6 5
 5 5 6 5 6 6 5 5 5 6 5 6 6 6 6 6 5 6 5 7 6 5 6 6 6 6 5 6 6 6 5 5 6 6 6 5 6
 5 5 5 5 5 6 6 5 6 5 5 5 5 5 5 5 5 6 5 7 6 6 6 7]
[6 5 7 6 5 6 5 6 4 5 5 5 6 5 6 6 7 5 5 4 7 6 6 4 6 5 5 7 5 6 5 6 5 6 7 7 5
 6 6 7 5 7 6 6 5 5 6 6 6 5 5 5 6 6 6 5 5 5 6 5 5 6 6 6 5 6 5 5 6 6 6 6 4 6
 5 6 5 5 5 6 6 5 6 6 6 5 6 5 5 5 5 6 4 5 7 6 6 5 6 5 8 6 6 6 5 5 5 5 7 5 6
 5 7 5 6 6 6 7 6 6 5 7 5 5 6 6 5 5 5 6 6 6 6 6 6 5 6 5 8 5 6 5 6 5 4 6 7 6
 5 6 6 5 5 5 6 6 3 6 6 6 6 6 6 6 5 5 6 6 6 6 5 5 5

In [55]:
from sklearn import metrics
cnf_matrix=metrics.confusion_matrix(y_test,y_pred)
print(cnf_matrix)
print()
print("Accuracy: ",metrics.accuracy_score(y_test,y_pred))
print("Precision: ",metrics.precision_score(y_test,y_pred,average='weighted'))
print("Recall: ",metrics.recall_score(y_test,y_pred,average='weighted'))
print("f1 score: ",metrics.f1_score(y_test,y_pred,average='weighted'))

[[ 0  0  1  1  0  0]
 [ 0  0  5  6  0  0]
 [ 0  0 89 45  1  0]
 [ 0  0 55 81  6  0]
 [ 0  0  4 21  2  0]
 [ 0  0  0  2  1  0]]

Accuracy:  0.5375
Precision:  0.49109453046953055
Recall:  0.5375
f1 score:  0.5101948084960556


C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [54]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.58      0.66      0.62       135
           6       0.52      0.57      0.54       142
           7       0.20      0.07      0.11        27
           8       0.00      0.00      0.00         3

    accuracy                           0.54       320
   macro avg       0.22      0.22      0.21       320
weighted avg       0.49      0.54      0.51       320



C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
